services:
  mysql:
    image: mysql:8.0
    container_name: reference-mysql
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refs
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data: